/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seth Veeper
 */
public class MainBoard extends javax.swing.JFrame {

    /**
     * Creates new form MainBoard
     */
    public int counter;
    
    public MainBoard() {
        initComponents();
        counter = 0;
        lblHead.setVisible(false);
        lblBody.setVisible(false);
        lblLeftArm.setVisible(false);
        lblRightArm.setVisible(false);
        lblLeftLeg.setVisible(false);
        lblRightLeg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        lblHead = new javax.swing.JLabel();
        lblBody = new javax.swing.JLabel();
        lblLeftArm = new javax.swing.JLabel();
        lblLeftLeg = new javax.swing.JLabel();
        lblRightArm = new javax.swing.JLabel();
        lblRightLeg = new javax.swing.JLabel();
        lblFrame = new javax.swing.JLabel();
        lblStand = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Click to add parts");
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head.png"))); // NOI18N
        getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        lblBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/body.png"))); // NOI18N
        getContentPane().add(lblBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        lblLeftArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limb_left.png"))); // NOI18N
        getContentPane().add(lblLeftArm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        lblLeftLeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limb_left.png"))); // NOI18N
        getContentPane().add(lblLeftLeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        lblRightArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limb_right.png"))); // NOI18N
        getContentPane().add(lblRightArm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblRightLeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limb_right.png"))); // NOI18N
        getContentPane().add(lblRightLeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        lblFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frame.png"))); // NOI18N
        getContentPane().add(lblFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblStand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stand.png"))); // NOI18N
        getContentPane().add(lblStand, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        counter++;
        
        switch(counter)
        {
            case 1:
                lblHead.setVisible(true);
                break;
            case 2:
                lblBody.setVisible(true);
                break;
            case 3:
                lblLeftArm.setVisible(true);
                break;
            case 4:
                lblRightArm.setVisible(true);
                break;
            case 5:
                lblLeftLeg.setVisible(true);
                break;
            case 6:
                lblRightLeg.setVisible(true);
                break;
            default:
                counter = 0;
                lblHead.setVisible(false);
                lblBody.setVisible(false);
                lblLeftArm.setVisible(false);
                lblRightArm.setVisible(false);
                lblLeftLeg.setVisible(false);
                lblRightLeg.setVisible(false);
                break;
            
        }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBody;
    private javax.swing.JLabel lblFrame;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblLeftArm;
    private javax.swing.JLabel lblLeftLeg;
    private javax.swing.JLabel lblRightArm;
    private javax.swing.JLabel lblRightLeg;
    private javax.swing.JLabel lblStand;
    // End of variables declaration//GEN-END:variables
}
