package practicedovah;
import java.util.Random; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seth Veeper
 */
public class Rune extends javax.swing.JPanel {

    private String Letter;
    private static String[] aryLetters = 
    {
      "A",
      "AA",
      "AH",
      "B",
      "D",
      "E",
      "EI",
      "EY",
      "F",
      "G",
      "H",
      "I",
      "II",
      "IR",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "OO",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "UR",
      "UU",
      "V",
      "W",
      "X",
      "Y",
      "Z"
    };
    private static Random rand = new Random();
    /**
     * Creates new form Rune
     */
    public Rune() {
        initComponents();
        this.Letter = aryLetters[rand.nextInt(aryLetters.length)];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRune = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        btnRune.setBackground(new java.awt.Color(0, 0, 0));
        btnRune.setToolTipText("");
        btnRune.setMinimumSize(new java.awt.Dimension(72, 74));
        btnRune.setPreferredSize(new java.awt.Dimension(75, 75));
        btnRune.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRuneMouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AA", "AH", "B", "D", "E", "EI", "EY", "F", "G", "H", "I", "II", "IR", "J", "K", "L", "M", "N", "O", "OO", "P", "Q", "R", "S", "T", "U", "UR", "UU", "V", "W", "X", "Y", "Z" }));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRune, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnRune, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRuneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuneMouseClicked
        // TODO add your handling code here:
        System.out.println("This rune is the letter " + this.Letter + ".");
    }//GEN-LAST:event_btnRuneMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRune;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
