package hellofx;
import java.util.Random;
/**
 *
 * @author Seth Veeper
 */
public class Bin extends javax.swing.JPanel {
    
    public static Random rand = new Random();
    
    /**
     * Creates new form Bin
     */
    public Bin() {
        initComponents();
        
        int input = rand.nextInt(2);//rand.nextInt(1);
        
        lblNumber.setText(Integer.toString(input));
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumber = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(40, 40));
        setMinimumSize(new java.awt.Dimension(35, 35));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(36, 36));

        lblNumber.setBackground(new java.awt.Color(0, 0, 0));
        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber.setText("0");
        lblNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        lblNumber.setMaximumSize(new java.awt.Dimension(40, 40));
        lblNumber.setMinimumSize(new java.awt.Dimension(35, 35));
        lblNumber.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNumber;
    // End of variables declaration//GEN-END:variables
}
